# Generated by Django 4.1.5 on 2023-06-17 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50, unique=True, verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Производитель оборудования',
                'verbose_name_plural': 'Производитель оборудования',
            },
        ),
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50, verbose_name='Модель оборудования')),
                ('type', models.CharField(choices=[('Модемы', 'Модемы'), ('Роутеры', 'Роутеры'), ('Zala', 'Zala'), ('Умный Дом', 'Умный Дом'), ('Смартфоны', 'Смартфоны'), ('Телевизоры', 'Телевизоры'), ('Игровые приставки', 'Игровые приставки'), ('Ноутбуки', 'Ноутбуки'), ('Планшеты', 'Планшеты'), ('Умные часы', 'Умные часы'), ('Электросамокаты', 'Электросамокаты'), ('Электровелосипеды', 'Электровелосипеды'), ('Пылесосы', 'Пылесосы'), ('Роботы-пылесосы', 'Роботы пылесосы'), ('Мойщики окон', 'Мойщики окон'), ('Кофемашины', 'Кофемашины'), ('Кофеварки', 'Кофеварки'), ('Кондиционеры', 'Кондиционеры'), ('Умные колонки', 'Умные колонки'), ('Аудиосистемы', 'Аудиосистемы'), ('Прочее оборудование', 'Прочее оборудование')], max_length=50, verbose_name='Вид оборудования')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.company', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
                'unique_together': {('company', 'model')},
            },
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('На продажу', 'На продажу'), ('Абонентское', 'Абонентское')], max_length=250, verbose_name='Назначение оборудования')),
            ],
            options={
                'verbose_name': 'Назначение оборудования',
                'verbose_name_plural': 'Назначение оборудования',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_centre', models.CharField(max_length=250, verbose_name='Сервисные центры')),
            ],
            options={
                'verbose_name': 'Сервисный центр',
                'verbose_name_plural': 'Сервисные центры',
            },
        ),
        migrations.CreateModel(
            name='Zala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('IPTV', 'IPTV'), ('Эфирная', 'Эфирная')], max_length=50, verbose_name='Тип оборудования')),
                ('image', models.ImageField(blank=True, null=True, upload_to='main/media')),
                ('actual', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Да', max_length=3, verbose_name='Актуально')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.models', verbose_name='Модель оборудования')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.purpose', verbose_name='Назначение')),
            ],
            options={
                'verbose_name': 'Zala',
                'verbose_name_plural': 'Zala',
            },
        ),
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=4, verbose_name='Диагональ экрана')),
                ('os', models.CharField(max_length=50, verbose_name='Операционная система')),
                ('support', models.CharField(max_length=70, verbose_name='Поддержка платформ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='main/media')),
                ('actual', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Да', max_length=3, verbose_name='Актуально')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.models', verbose_name='Модель оборудования')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.purpose', verbose_name='Назначение')),
            ],
            options={
                'verbose_name': 'Умные часы',
                'verbose_name_plural': 'Умные часы',
            },
        ),
        migrations.CreateModel(
            name='Vacuum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Робот пылесос', 'Робот пылесос'), ('Вертикальный пылесос', 'Вертикальный пылесос'), ('Мойщик окон', 'Мойщик окон')], default='Робот пылесос', max_length=25, verbose_name='Тип пылесоса')),
                ('image', models.ImageField(blank=True, null=True, upload_to='main/media')),
                ('actual', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Да', max_length=3, verbose_name='Актуально')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.models', verbose_name='Модель оборудования')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.purpose', verbose_name='Назначение')),
            ],
            options={
                'verbose_name': 'Устройство для уборки',
                'verbose_name_plural': 'Устройства для уборки',
            },
        ),
        migrations.CreateModel(
            name='Tv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.FloatField(max_length=4, verbose_name='Диагональ экрана')),
                ('resolution', models.CharField(max_length=20, verbose_name='Разрешение экрана')),
                ('smart', models.CharField(max_length=40, verbose_name='Наличие SmartTV')),
                ('image', models.ImageField(blank=True, null=True, upload_to='main/media')),
                ('actual', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Да', max_length=3, verbose_name='Актуально')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.models', verbose_name='Модель оборудования')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.purpose', verbose_name='Назначение')),
            ],
            options={
                'verbose_name': 'Телевизор',
                'verbose_name_plural': 'Телевизоры',
            },
        ),
        migrations.CreateModel(
            name='TesterTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worktime', models.TextField(max_length=150, verbose_name='Время работы тестировщика')),
                ('onduty', models.BooleanField(verbose_name='Тестировщик на месте')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.service', verbose_name='Сервисный центр')),
            ],
            options={
                'verbose_name': 'Время работы тестировщика',
                'verbose_name_plural': 'Время работы тестировщика',
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип соединения')),
                ('power', models.CharField(blank=True, max_length=50, null=True, verbose_name='Выходная мощность')),
                ('battery', models.CharField(blank=True, max_length=80, null=True, verbose_name='Источник питания')),
                ('image', models.ImageField(blank=True, null=True, upload_to='main/media')),
                ('actual', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Да', max_length=3, verbose_name='Актуально')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.models', verbose_name='Модель оборудования')),
            ],
            options={
                'verbose_name': 'Аудиосистема',
                'verbose_name_plural': 'Аудиосистемы',
            },
        ),
        migrations.CreateModel(
            name='SmartSpeaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bluetooth', models.CharField(max_length=50, verbose_name='Версия Bluetooth')),
                ('power', models.CharField(max_length=50, verbose_name='Номинальная мощность')),
                ('control', models.CharField(max_length=50, verbose_name='Управление')),
                ('image', models.ImageField(blank=True, null=True, upload_to='main/media')),
                ('actual', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Да', max_length=3, verbose_name='Актуально')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.models', verbose_name='Модель оборудования')),
            ],
            options={
                'verbose_name': 'Умная колонка',
                'verbose_name_plural': 'Умные колонки',
            },
        ),
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor', models.CharField(max_length=30, verbose_name='Процессор')),
                ('size', models.FloatField(max_length=4, verbose_name='Диагональ экрана')),
                ('ddr', models.PositiveSmallIntegerField(verbose_name='Объём оперативной памяти')),
                ('memory', models.PositiveSmallIntegerField(verbose_name='Объём накопителя')),
                ('image', models.ImageField(blank=True, null=True, upload_to='main/media')),
                ('actual', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Да', max_length=3, verbose_name='Актуально')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.models', verbose_name='Модель оборудования')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.purpose', verbose_name='Назначение')),
            ],
            options={
                'verbose_name': 'Смартфон',
                'verbose_name_plural': 'Смартфоны',
            },
        ),
        migrations.CreateModel(
            name='SmartHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Тип оборудования')),
                ('image', models.ImageField(blank=True, null=True, upload_to='main/media')),
                ('actual', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Да', max_length=3, verbose_name='Актуально')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.models', verbose_name='Модель оборудования')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.purpose', verbose_name='Назначение')),
            ],
            options={
                'verbose_name': 'Умный Дом',
                'verbose_name_plural': 'Умный Дом',
            },
        ),
        migrations.CreateModel(
            name='Scooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxspeed', models.CharField(max_length=50, verbose_name='Максимальная скорость и дистанция')),
                ('power', models.CharField(max_length=50, verbose_name='Мощность мотора')),
                ('accumulator', models.CharField(max_length=50, verbose_name='Аккумулятор')),
                ('maxload', models.CharField(max_length=50, verbose_name='Максимальная нагрузка')),
                ('weight', models.CharField(max_length=50, verbose_name='Вес')),
                ('chargetime', models.CharField(max_length=50, verbose_name='Время заряда')),
                ('image', models.ImageField(blank=True, null=True, upload_to='main/media')),
                ('actual', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Да', max_length=3, verbose_name='Актуально')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.models', verbose_name='Модель оборудования')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.purpose', verbose_name='Назначение')),
            ],
            options={
                'verbose_name': 'Электросамокат',
                'verbose_name_plural': 'Электросамокаты',
            },
        ),
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ADSL', 'ADSL'), ('VDSL', 'VDSL'), ('PON', 'PON'), ('На продажу', 'На продажу')], max_length=50, verbose_name='Тип модема')),
                ('wifi', models.CharField(choices=[('+', '+'), ('-', '-')], max_length=50, verbose_name='Наличие Wi-Fi')),
                ('wifi_freq', models.CharField(choices=[('2,4', '2,4'), ('2,4/5', '2,4/5'), ('-', '-')], max_length=50, verbose_name='Диапазон Wi-Fi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='main/media')),
                ('actual', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Да', max_length=3, verbose_name='Актуально')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.models', verbose_name='Модель оборудования')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.purpose', verbose_name='Назначение')),
            ],
            options={
                'verbose_name': 'Модем',
                'verbose_name_plural': 'Модемы',
            },
        ),
        migrations.CreateModel(
            name='Pad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.FloatField(max_length=4, verbose_name='Диагональ экрана')),
                ('ddr', models.PositiveSmallIntegerField(verbose_name='Объём оперативной памяти')),
                ('memory', models.PositiveSmallIntegerField(verbose_name='Объём накопителя')),
                ('image', models.ImageField(blank=True, null=True, upload_to='main/media')),
                ('actual', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Да', max_length=3, verbose_name='Актуально')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.models', verbose_name='Модель оборудования')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.purpose', verbose_name='Назначение')),
            ],
            options={
                'verbose_name': 'Планшет',
                'verbose_name_plural': 'Планшеты',
            },
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Тип оборудования')),
                ('image', models.ImageField(blank=True, null=True, upload_to='main/media')),
                ('actual', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Да', max_length=3, verbose_name='Актуально')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.models', verbose_name='Модель оборудования')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.purpose', verbose_name='Назначение')),
            ],
            options={
                'verbose_name': 'Разное',
                'verbose_name_plural': 'Разное',
            },
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.FloatField(max_length=4, verbose_name='Диагональ экрана')),
                ('cpu', models.CharField(max_length=20, verbose_name='Модель процессора')),
                ('ddr', models.PositiveSmallIntegerField(verbose_name='Объём оперативной памяти')),
                ('memory', models.CharField(max_length=20, verbose_name='Вид и объём накопителя')),
                ('image', models.ImageField(blank=True, null=True, upload_to='main/media')),
                ('actual', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Да', max_length=3, verbose_name='Актуально')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.models', verbose_name='Модель оборудования')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.purpose', verbose_name='Назначение')),
            ],
            options={
                'verbose_name': 'Ноутбук',
                'verbose_name_plural': 'Ноутбуки',
            },
        ),
        migrations.CreateModel(
            name='Conditioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conditioner_type', models.CharField(max_length=50, verbose_name='Тип кондиционера')),
                ('power', models.CharField(max_length=50, verbose_name='Мощность охлаждения/обогрева ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='main/media')),
                ('actual', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Да', max_length=3, verbose_name='Актуально')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.models', verbose_name='Модель оборудования')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.purpose', verbose_name='Назначение')),
            ],
            options={
                'verbose_name': 'Кондиционер',
                'verbose_name_plural': 'Кондиционеры',
            },
        ),
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod', models.CharField(choices=[('Кофеварка', 'Кофеварка'), ('Кофемашина', 'Кофемашина')], max_length=50, verbose_name='Вид устройства')),
                ('pressure', models.PositiveSmallIntegerField(verbose_name='Давление (Бар)')),
                ('capucinator', models.CharField(choices=[('Ручной', 'Ручной'), ('Автоматичесий', 'Автоматичесий')], max_length=50, verbose_name='Тип капучинатора')),
                ('control', models.CharField(choices=[('Механическое', 'Механическое'), ('Электронное', 'Электронное'), ('Сенсорное', 'Сенсорное')], max_length=50, verbose_name='Управление')),
                ('image', models.ImageField(blank=True, null=True, upload_to='main/media')),
                ('actual', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Да', max_length=3, verbose_name='Актуально')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.models', verbose_name='Модель оборудования')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.purpose', verbose_name='Назначение')),
            ],
            options={
                'verbose_name': 'Кофемашина',
                'verbose_name_plural': 'Кофемашины',
            },
        ),
        migrations.CreateModel(
            name='Bikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveSmallIntegerField(verbose_name='Размер колеса')),
                ('image', models.ImageField(blank=True, null=True, upload_to='main/media')),
                ('actual', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Да', max_length=3, verbose_name='Актуально')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.models', verbose_name='Модель оборудования')),
            ],
            options={
                'verbose_name': 'Электровелосипед',
                'verbose_name_plural': 'Электровелосипеды',
            },
        ),
        migrations.CreateModel(
            name='Available',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.CharField(choices=[('+', '+'), ('-', '-')], default='-', max_length=20, verbose_name='Наличие')),
                ('quantity', models.PositiveSmallIntegerField(default='0', verbose_name='Количество')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.models', verbose_name='Модель оборудования')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.service', verbose_name='Сервисный центр')),
            ],
            options={
                'verbose_name': 'Наличие оборудования',
                'verbose_name_plural': 'Наличие оборудования',
                'ordering': ['model'],
                'unique_together': {('service', 'model')},
            },
        ),
    ]
