# Generated by Django 4.1.5 on 2023-10-19 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddFilter1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Параметр фильтра')),
            ],
            options={
                'verbose_name': 'Значение фильтра',
                'verbose_name_plural': 'Значения фильтра',
            },
        ),
        migrations.CreateModel(
            name='AddFilterName1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Название параметра фильтра')),
            ],
            options={
                'verbose_name': 'Название фильтра',
                'verbose_name_plural': 'Названия фильтра',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50, unique=True, verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Производитель оборудования',
                'verbose_name_plural': 'Производитель оборудования',
            },
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('На продажу', 'На продажу'), ('Абонентское', 'Абонентское')], max_length=250, verbose_name='Назначение оборудования')),
            ],
            options={
                'verbose_name': 'Назначение оборудования',
                'verbose_name_plural': 'Назначение оборудования',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_centre', models.CharField(max_length=250, verbose_name='Сервисные центры')),
            ],
            options={
                'verbose_name': 'Сервисный центр',
                'verbose_name_plural': 'Сервисные центры',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, unique=True, verbose_name='Тип оборудования')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True, verbose_name='Ссылка')),
                ('purpose', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.purpose')),
            ],
            options={
                'verbose_name': 'Тип оборудования',
                'verbose_name_plural': 'Тип оборудования',
            },
        ),
        migrations.CreateModel(
            name='TesterTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worktime', models.TextField(max_length=150, verbose_name='Время работы тестировщика')),
                ('onduty', models.BooleanField(verbose_name='Тестировщик на месте')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.service', verbose_name='Сервисный центр')),
            ],
            options={
                'verbose_name': 'Время работы тестировщика',
                'verbose_name_plural': 'Время работы тестировщика',
            },
        ),
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50, verbose_name='Модель оборудования')),
                ('actual', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Да', max_length=3, verbose_name='Актуально')),
                ('image', models.ImageField(blank=True, null=True, upload_to=main.models.Models.photo_upload)),
                ('add_filter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.addfilter1', verbose_name='Значение фильтра')),
                ('add_filter_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.addfiltername1', verbose_name='Название дополнительного фильтра')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.company', verbose_name='Производитель')),
                ('type_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.type', verbose_name='Тип оборудования')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
                'unique_together': {('company', 'model')},
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.service', verbose_name='Сервисный центр')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Привязка админов к СЦ',
                'verbose_name_plural': 'Привязки админов к СЦ',
            },
        ),
        migrations.CreateModel(
            name='Available',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.CharField(choices=[('+', '+'), ('-', '-')], default='-', max_length=20, verbose_name='Наличие')),
                ('quantity', models.PositiveSmallIntegerField(default='0', verbose_name='Количество')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.models', verbose_name='Модель оборудования')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.service', verbose_name='Сервисный центр')),
            ],
            options={
                'verbose_name': 'Наличие оборудования',
                'verbose_name_plural': 'Наличие оборудования',
                'ordering': ['model'],
                'unique_together': {('service', 'model')},
            },
        ),
    ]
