# Generated by Django 4.1.5 on 2023-06-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacuum',
            name='type',
            field=models.CharField(choices=[('Робот', 'Робот'), ('Вертикальный', 'Вертикальный'), ('Мойщики окон', 'Мойщики окон')], default='Робот', max_length=15, verbose_name='Тип пылесоса'),
        ),
    ]
