# Generated by Django 4.1.5 on 2023-09-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddFilterName1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Название параметра фильтра')),
            ],
            options={
                'verbose_name': 'Название фильтра',
                'verbose_name_plural': 'Названия фильтра',
            },
        ),
    ]
