# Generated by Django 4.1.5 on 2023-03-23 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип соединения')),
                ('power', models.CharField(blank=True, max_length=50, null=True, verbose_name='Выходная мощность')),
                ('battery', models.CharField(blank=True, max_length=80, null=True, verbose_name='Источник питания')),
                ('image', models.ImageField(blank=True, null=True, upload_to='main/media')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.models', verbose_name='Модель оборудования')),
            ],
            options={
                'verbose_name': 'Аудиосистема',
                'verbose_name_plural': 'Аудиосистемы',
            },
        ),
    ]
