# Generated by Django 4.1.3 on 2023-01-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='router',
            name='image',
            field=models.ImageField(blank=True, upload_to='main/media'),
        ),
    ]
