# Generated by Django 4.1.5 on 2023-04-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_speaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='actual',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Да', max_length=3, verbose_name='Актуально'),
        ),
        migrations.AlterUniqueTogether(
            name='models',
            unique_together={('company', 'model')},
        ),
    ]
