# Generated by Django 4.1.5 on 2023-02-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_coffee_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models',
            name='type',
            field=models.CharField(choices=[('Модемы', 'Модемы'), ('Zala', 'Zala'), ('Умный Дом', 'Умный Дом'), ('Смартфоны', 'Смартфоны'), ('Телевизоры', 'Телевизоры'), ('Ноутбуки', 'Ноутбуки'), ('Планшеты', 'Планшеты'), ('Умные часы', 'Умные часы'), ('Электросамокаты', 'Электросамокаты'), ('Роботы пылесосы', 'Роботы пылесосы'), ('Кофе-машины', 'Кофе-машины'), ('Кондиционеры', 'Кондиционеры'), ('Умные колонки', 'Умные колонки'), ('Прочее оборудование', 'Прочее оборудование')], max_length=50, verbose_name='Вид оборудования'),
        ),
        migrations.AlterField(
            model_name='router',
            name='type',
            field=models.CharField(choices=[('ADSL', 'ADSL'), ('VDSL', 'VDSL'), ('PON', 'PON'), ('На продажу', 'На продажу')], max_length=50, verbose_name='Тип модема'),
        ),
    ]
