# Generated by Django 4.1.5 on 2023-12-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_employee_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['company'], 'verbose_name': 'Производитель оборудования', 'verbose_name_plural': 'Производитель оборудования'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ['type'], 'verbose_name': 'Тип оборудования', 'verbose_name_plural': 'Тип оборудования'},
        ),
        migrations.AddField(
            model_name='models',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Стоимость'),
        ),
        migrations.AddField(
            model_name='models',
            name='split_period',
            field=models.IntegerField(blank=True, null=True, verbose_name='Период рассрочки'),
        ),
    ]
