# Generated by Django 4.1.5 on 2023-09-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_addfiltername1'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddFilter1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Параметр фильтра')),
            ],
            options={
                'verbose_name': 'Значение фильтра',
                'verbose_name_plural': 'Значения фильтра',
            },
        ),
    ]
