# Generated by Django 4.1.5 on 2023-06-21 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_vacuum_type'),
        ('main', '0002_console'),
    ]

    operations = [
    ]
