# Generated by Django 4.1.5 on 2023-04-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_coffee_actual_alter_models_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditioner',
            name='actual',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Да', max_length=3, verbose_name='Актуально'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='actual',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Да', max_length=3, verbose_name='Актуально'),
        ),
        migrations.AddField(
            model_name='other',
            name='actual',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Да', max_length=3, verbose_name='Актуально'),
        ),
        migrations.AddField(
            model_name='pad',
            name='actual',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Да', max_length=3, verbose_name='Актуально'),
        ),
        migrations.AddField(
            model_name='router',
            name='actual',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Да', max_length=3, verbose_name='Актуально'),
        ),
        migrations.AddField(
            model_name='scooter',
            name='actual',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Да', max_length=3, verbose_name='Актуально'),
        ),
        migrations.AddField(
            model_name='smarthome',
            name='actual',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Да', max_length=3, verbose_name='Актуально'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='actual',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Да', max_length=3, verbose_name='Актуально'),
        ),
        migrations.AddField(
            model_name='smartspeaker',
            name='actual',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Да', max_length=3, verbose_name='Актуально'),
        ),
        migrations.AddField(
            model_name='speaker',
            name='actual',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Да', max_length=3, verbose_name='Актуально'),
        ),
        migrations.AddField(
            model_name='tv',
            name='actual',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Да', max_length=3, verbose_name='Актуально'),
        ),
        migrations.AddField(
            model_name='vacuum',
            name='actual',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Да', max_length=3, verbose_name='Актуально'),
        ),
        migrations.AddField(
            model_name='watch',
            name='actual',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Да', max_length=3, verbose_name='Актуально'),
        ),
        migrations.AddField(
            model_name='zala',
            name='actual',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Да', max_length=3, verbose_name='Актуально'),
        ),
    ]
