# Generated by Django 4.1.5 on 2023-08-09 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_models_type_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='models',
            name='type',
        ),
    ]
