# Generated by Django 4.1.5 on 2023-06-21 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_merge_0002_alter_vacuum_type_0002_console'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='console',
            options={'verbose_name': 'Игровую приставку', 'verbose_name_plural': 'Игровые приставки'},
        ),
        migrations.AlterField(
            model_name='models',
            name='type',
            field=models.CharField(choices=[('Модемы', 'Модемы'), ('Роутеры', 'Роутеры'), ('Zala', 'Zala'), ('Умный Дом', 'Умный Дом'), ('Смартфоны', 'Смартфоны'), ('Телевизоры', 'Телевизоры'), ('Игровые приставки', 'Игровые приставки'), ('Ноутбуки', 'Ноутбуки'), ('Планшеты', 'Планшеты'), ('Умные часы', 'Умные часы'), ('Электросамокаты', 'Электросамокаты'), ('Электровелосипеды', 'Электровелосипеды'), ('Пылесосы', 'Пылесосы'), ('Роботы-пылесосы', 'Роботы пылесосы'), ('Мойщики окон', 'Мойщики окон'), ('Кофемашины', 'Кофемашины'), ('Кофеварки', 'Кофеварки'), ('Электрогрили', 'Электрогрили'), ('Кондиционеры', 'Кондиционеры'), ('Умные колонки', 'Умные колонки'), ('Аудиосистемы', 'Аудиосистемы'), ('Прочее оборудование', 'Прочее оборудование')], max_length=50, verbose_name='Вид оборудования'),
        ),
        migrations.AlterField(
            model_name='vacuum',
            name='type',
            field=models.CharField(choices=[('Робот пылесос', 'Робот пылесос'), ('Вертикальный пылесос', 'Вертикальный пылесос'), ('Мойщик окон', 'Мойщик окон')], default='Робот пылесос', max_length=25, verbose_name='Тип пылесоса'),
        ),
        migrations.CreateModel(
            name='Cooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Электрогриль', 'Электрогриль')], max_length=25, verbose_name='Вид устройства')),
                ('image', models.ImageField(blank=True, null=True, upload_to='main/media')),
                ('actual', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Да', max_length=3, verbose_name='Актуально')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.models', verbose_name='Модель оборудования')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.purpose', verbose_name='Назначение')),
            ],
            options={
                'verbose_name': 'Технику для кухни',
                'verbose_name_plural': 'Техника для кухни',
            },
        ),
    ]
