# Generated by Django 4.1.5 on 2023-12-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_models_full_price_alter_models_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='models',
            name='full_price',
        ),
        migrations.AlterField(
            model_name='models',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Стоимость'),
        ),
    ]
