# Generated by Django 4.1.5 on 2023-04-27 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_conditioner_actual_notebook_actual_other_actual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models',
            name='type',
            field=models.CharField(choices=[('Модемы', 'Модемы'), ('Роутеры', 'Роутеры'), ('Zala', 'Zala'), ('Умный Дом', 'Умный Дом'), ('Смартфоны', 'Смартфоны'), ('Телевизоры', 'Телевизоры'), ('Ноутбуки', 'Ноутбуки'), ('Планшеты', 'Планшеты'), ('Умные часы', 'Умные часы'), ('Электросамокаты', 'Электросамокаты'), ('Электровелосипеды', 'Электровелосипеды'), ('Роботы пылесосы', 'Роботы пылесосы'), ('Кофемашины', 'Кофемашины'), ('Кофеварки', 'Кофеварки'), ('Кондиционеры', 'Кондиционеры'), ('Умные колонки', 'Умные колонки'), ('Аудиосистемы', 'Аудиосистемы'), ('Прочее оборудование', 'Прочее оборудование')], max_length=50, verbose_name='Вид оборудования'),
        ),
        migrations.CreateModel(
            name='Bikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50, verbose_name='Размер колеса')),
                ('image', models.ImageField(blank=True, null=True, upload_to='main/media')),
                ('actual', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Да', max_length=3, verbose_name='Актуально')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.models', verbose_name='Модель оборудования')),
            ],
            options={
                'verbose_name': 'Электровелосипед',
                'verbose_name_plural': 'Электровелосипеды',
            },
        ),
    ]
