# Generated by Django 4.1.5 on 2023-07-04 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_scooter_accumulator_remove_scooter_chargetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notebook',
            name='cpu',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='ddr',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='memory',
        ),
    ]
