# Generated by Django 4.1.5 on 2023-04-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_models_type_bikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikes',
            name='size',
            field=models.PositiveSmallIntegerField(max_length=4, verbose_name='Размер колеса'),
        ),
    ]
