# Generated by Django 4.1.5 on 2023-06-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_models_type_alter_vacuum_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacuum',
            name='type',
            field=models.CharField(choices=[('Робот пылесос', 'Робот пылесос'), ('Вертикальный пылесос', 'Вертикальный пылесос'), ('Мойщик окон', 'Мойщик окон')], default='Робот', max_length=25, verbose_name='Тип пылесоса'),
        ),
    ]
