# Generated by Django 4.1.5 on 2023-07-31 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_notebook_cpu_remove_notebook_ddr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='type',
            field=models.CharField(choices=[('Ноутбук', 'Ноутбук'), ('Системный блок', 'Системный блок')], default='Ноутбук', max_length=25, verbose_name='Тип пылесоса'),
        ),
        migrations.AlterField(
            model_name='models',
            name='type',
            field=models.CharField(choices=[('Модемы', 'Модемы'), ('Роутеры', 'Роутеры'), ('Zala', 'Zala'), ('Умный Дом', 'Умный Дом'), ('Смартфоны', 'Смартфоны'), ('Телевизоры', 'Телевизоры'), ('Игровые приставки', 'Игровые приставки'), ('Компьютеры', 'Компьютеры'), ('Ноутбуки', 'Ноутбуки'), ('Планшеты', 'Планшеты'), ('Умные часы', 'Умные часы'), ('Электросамокаты', 'Электросамокаты'), ('Электровелосипеды', 'Электровелосипеды'), ('Пылесосы', 'Пылесосы'), ('Роботы-пылесосы', 'Роботы пылесосы'), ('Мойщики окон', 'Мойщики окон'), ('Кофемашины', 'Кофемашины'), ('Кофеварки', 'Кофеварки'), ('Электрогрили', 'Электрогрили'), ('Соковыжималки', 'Соковыжималки'), ('Сушилки', 'Сушилки'), ('Кондиционеры', 'Кондиционеры'), ('Умные колонки', 'Умные колонки'), ('Аудиосистемы', 'Аудиосистемы'), ('Прочее оборудование', 'Прочее оборудование')], max_length=50, verbose_name='Вид оборудования'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='size',
            field=models.FloatField(blank=True, max_length=4, null=True, verbose_name='Диагональ экрана'),
        ),
    ]
