# Generated by Django 4.1.5 on 2023-09-27 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_employee_department_employee_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Привязка админов к СЦ', 'verbose_name_plural': 'Привязки админов к СЦ'},
        ),
        migrations.CreateModel(
            name='FilterMix1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addfilter1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.addfilter1', verbose_name='Название фильтра')),
                ('addfiltername1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.addfiltername1', verbose_name='Значение')),
                ('type_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.type', verbose_name='Тип оборудования')),
            ],
        ),
    ]
