# Generated by Django 4.1.5 on 2023-02-13 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_router_wifi_freq'),
    ]

    operations = [
        migrations.CreateModel(
            name='TesterTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worktime', models.CharField(max_length=150, verbose_name='Время работы тестировщика')),
                ('onduty', models.BooleanField(verbose_name='Тестировщик на месте')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.service', verbose_name='Сервисный центр')),
            ],
        ),
    ]
