# Generated by Django 5.0a1 on 2024-03-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_models_full_price_alter_models_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='models',
            name='warranty',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Гарантия'),
        ),
    ]
