# Generated by Django 4.1.5 on 2023-07-31 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_notebook_type_alter_models_type_alter_notebook_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notebook',
            options={'verbose_name': 'Ноутбуки и компьютерное оборудование', 'verbose_name_plural': 'Ноутбуки и компьютерное оборудование'},
        ),
    ]
