# Generated by Django 4.1.5 on 2023-02-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_testertime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testertime',
            options={'verbose_name': 'Время работы тестировщика', 'verbose_name_plural': 'Время работы тестировщика'},
        ),
        migrations.AlterField(
            model_name='testertime',
            name='worktime',
            field=models.TextField(max_length=150, verbose_name='Время работы тестировщика'),
        ),
    ]
