# Generated by Django 4.1.5 on 2023-02-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_testertime_options_alter_testertime_worktime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models',
            name='type',
            field=models.CharField(choices=[('Модемы', 'Модемы'), ('Роутеры', 'Роутеры'), ('Zala', 'Zala'), ('Умный Дом', 'Умный Дом'), ('Смартфоны', 'Смартфоны'), ('Телевизоры', 'Телевизоры'), ('Ноутбуки', 'Ноутбуки'), ('Планшеты', 'Планшеты'), ('Умные часы', 'Умные часы'), ('Электросамокаты', 'Электросамокаты'), ('Роботы пылесосы', 'Роботы пылесосы'), ('Кофе-машины', 'Кофе-машины'), ('Кондиционеры', 'Кондиционеры'), ('Умные колонки', 'Умные колонки'), ('Прочее оборудование', 'Прочее оборудование')], max_length=50, verbose_name='Вид оборудования'),
        ),
    ]
